### ISSUE TITLE
Does not fit into ImageReadWriter framework 

### ISSUE THREAD

**Issue by tblanchard** [pharo-contributions/Athens-SVG#5]
Most images are fetched via ImageReadWriter subclasses.

ImageReadWriter formFromFileNamed: aFileReference

Add a subclass of ImageReadWriter to make it as easy to handle svg images as png, jpg, and gif.

**Comment by pavel-krivanek** [comment]
closed via https://github.com/pharo-contributions/Athens-SVG/pull/6
