### ISSUE TITLE
Looks like Athens-SVG does not work on pharo 9

### ISSUE THREAD

**Issue by akevalion** [pharo-contributions/Athens-SVG#9]
I have try to load this version of athens-svg and it does not work well on pharo 9 but it works  pharo 8.

The reason is there are some missing classes like  `StandardFileStream`

```Smalltalk
isSupportedImplementation
	^ XMLClassFinder hasClassNamed: #StandardFileStream
```

Present in Pharo8 but not in Pharo9

**Comment by pavel-krivanek** [comment]
Well, that is not a problem of Athens-SVG but of XML Parser [1] that has no working version for Pharo 9, I will close it here

[1] https://github.com/pharo-contributions/XML-XMLParser
